CREATE DATABASE IF NOT EXISTS fyhqqfyh CHARACTER utf8;
CREATE TABLE IF NOT EXISTS username(
username VARCHAR (20) NOT NULL ,
password VARCHAR (20) NOT NULL ,
id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
);